# Generated by Django 4.0.3 on 2022-03-08 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_attendance_note_school_student_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.AlterField(
            model_name='school',
            name='teachersAtSchool',
            field=models.ManyToManyField(blank=True, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, null=True, to='account.attendance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='account.teacher'),
        ),
    ]
