# Generated by Django 4.0.3 on 2022-03-09 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_teacher_schoolsteachingat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='teachersAtSchool',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
