# Generated by Django 4.0.3 on 2022-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_school_teachersatschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='teachersAtSchool',
            field=models.ManyToManyField(blank=True, to='account.teacher'),
        ),
    ]
