# Generated by Django 4.0.3 on 2022-03-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.note'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='account.attendance'),
        ),
    ]
