# Generated by Django 4.0.3 on 2022-03-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_student_notes_alter_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schoolsTeachingAt',
        ),
    ]
